### ISSUE TITLE
type-datapatches to fix values actually belonging to other fields as well as the field at issue

### ISSUE THREAD

**Issue by jbothma** [opensanctions/opensanctions#1160]
**Is your feature request related to a problem? Please describe.**

Sometimes values are mixed to the wrong fields at the source very occasionally without a nice way to parse them out

**Describe the solution you'd like**

I'd like type datapatches to be able to map values to more than one prop

**Describe alternatives you've considered**

writing code to try and parse it out conditionally, but that's a bit of a sledgehammer for a handful of issues in hundreds of items

**Additional context**

How about

```yaml
type.address:
  options:
    - match: Branch Office 6: Shop number 237, Shah Zada Market (also known as Sarai Shahzada), Puli Khishti area, Police District 1, Kabul, Afghanistan, Telephone: +93-202-103386, +93-202-101714, 0202-104748, Mobile: +93-797-059059, +93-702-222222, e-mail: helmand_exchange_msp@yahoo.com
      - value: Shop number 237, Shah Zada Market (also known as Sarai Shahzada), Puli Khishti area, Police District 1, Kabul, Afghanistan
        props:
          phone:
            - +93-202-103386
            - +93-202-101714
            - 0202-104748
            - +93-797-059059
            - +93-702-222222
         email: helmand_exchange_msp@yahoo.com
```

**Comment by pudo** [comment]
This is really funny, I was just chatting with @nvmbrasserie yesterday about how we should do this. Very +1.

**Comment by goose-life** [comment]
@jbothma reckon this can be closed now? what with review and all

**Comment by pudo** [comment]
Still very much alive, and I just hit a batch of these head-on while cleaning up the lookups in `eu_journal_sanctions`, so here's a concrete proposal plus some numbers.

Short version: the plumbing for the original request is already ~90% there, and there's a second, bigger win sitting right next to it.

## The mechanics already allow multi-prop

`prop_lookup()` in `zavod/zavod/runtime/lookups.py` already returns `list[tuple[Property, str]]` — a list of *(prop, value)* pairs — and `value_clean()` in `zavod/zavod/runtime/cleaning.py` iterates that list, cleaning and validating each pair against **its own** property. So a phone number extracted out of an address cell would get phone cleaning for free, and a bogus one would get rejected rather than trusted.

datapatch's `Result.__getattr__` already surfaces any unrecognised key in the option dict, so `result.props` works without a datapatch release. And `prop:` (reroute the whole value) is the degenerate case that exists today.

It's a few lines in `prop_lookup()`.

## Proposed syntax

```yaml
type.address:
  options:
    - match: "Krasnoarmeyskaya Str. 103, 241050 Bryansk, Bryanskaya Oblast, Russian Federation Type of entity: Joint Stock Company Registration number: 1023202741781 Tax Identification Number: 3234043140 Website: https://group-kremny.ru/ Email: group@kremny.032.ru Telephone: + 7 (4832) 41-43-11, + 7 (4832) 41-42-34"
      value: Krasnoarmeyskaya Str. 103, 241050 Bryansk, Bryanskaya Oblast, Russian Federation
      props:
        legalForm: Joint Stock Company
        registrationNumber: "1023202741781"
        taxNumber: "3234043140"
        website: https://group-kremny.ru/
        email: group@kremny.032.ru
        phone:
          - "+ 7 (4832) 41-43-11"
          - "+ 7 (4832) 41-42-34"
```

Three rules that make it behave:

1. **`value` / `values` keep their current meaning** — the property being cleaned. `props:` is purely additive, so every existing option in every dataset stays valid.
2. **`value: null` composes with `props:`** to mean "none of this belongs here, all of it belongs there". Keeping the two keys orthogonal gets that case for free instead of needing a third key.
3. **`original_value` on every fanned-out statement stays the whole source cell**, so you can trace a phone number back to the address cell it was buried in. `value_clean()` already sets `ORIGIN_LOOKUP` when the item differs from the input.

A prop that isn't on the entity's schema should warn and skip, matching what the existing invalid-`prop:`-rewrite path does, rather than failing the crawl.

## The bigger win: named captures with substitution

The ugly part of the original example isn't `props:` — it's retyping 120 characters of a 280-character match as the `value`. That same repetition is why `type.date` in `eu_journal_sanctions` now has **227 options**:

```yaml
type.date:
  lowercase: true
  options:
    - regex: '^(?:approximately|circa|ca\.|around|probably|before)\s+(?P<year>\d{4})$'
      value: "{year}"
    - regex: '^between\s+(?P<from>\d{4})\s+and\s+(?P<to>\d{4})(?:\s*\(approximately\))?$'
      values: ["{from}", "{to}"]
```

Measured against the file as committed: **78 of the 227 options (101 distinct match strings) collapse into 5 regex options.** More importantly it ends the treadmill — the next act that prints `Approximately 1971` just works instead of needing a new entry. These shapes come from the EU acts reproducing UN Security Council listings verbatim, so they recur indefinitely.

It composes with `props:` to remove the repetition there too:

```yaml
- regex: '^(?P<addr>.+?)\s+Registration number:\s*(?P<reg>\d+)\s+Tax Identification Number:\s*(?P<tin>\d+)'
  value: "{addr}"
  props:
    registrationNumber: "{reg}"
    taxNumber: "{tin}"
```

Details I'd want nailed down:

- Named groups only. `\1` fights YAML escaping and reads badly.
- `{{` escapes a literal brace.
- **A `{name}` with no corresponding group is a load-time config error, not an empty string.** Silent empties are exactly how bad data gets in.
- The substituted result still goes through normal type cleaning.

`regex:` already exists on datapatch options; only the substitution is new.

## What I'd deliberately leave out

- **Cross-entity fan-out** — no minting an `Address` or `Passport` entity from a lookup. That turns lookups into a second, worse crawler. (The passport issue/expiry dates that would want it have no home on `Person` anyway.)
- **Conditionals or explicit option ordering.** datapatch raises `LookupException` on equal-weight ambiguity today; keep it loud. Multi-prop raises the cost of a wrong match, so this isn't the moment to soften that.
- **A general "labelled run" splitter** (`Type of entity: … Registration number: …` → columns automatically). Tempting, since that shape is most of what's broken here — but it's a parser in disguise, and label→column mapping belongs in the transcription layer, not the dataset YAML.

## Re: does review supersede this?

I don't think so. Review covers **names**. Every case I ran into is a non-name property with no review path. Concretely, in `eu_journal_sanctions` today there are five address cells where the only options are "emit a 328-character address" or "truncate and drop the data" — I took the second, which bins a registration number, a TIN, a `legalForm`, three websites and several emails. Plus the Branch Office 6 example in the issue description, where six phone numbers and an email die the same way. `props:` recovers all of it.

## One gotcha worth designing around

The lookup matches the **raw source value**, and `issues.json` doesn't always show you that value. The Kremny address above logs as `Website: https://***:***@kremny.032.ru` — credential-shaped URLs get redacted before the issue record is written — while the actual cell reads `Website: https://group-kremny.ru/ Email: group@kremny.032.ru`. A maintainer copying the match string out of the issue log writes an option that never fires, and the only signal is an `Unused lookup option` line buried in the run log. That cost me a debugging round.

With `props:` the stakes go up, because a non-matching option silently loses the fanned-out data too. A `--strict-lookups` mode, or just promoting unmatched/unused options into the run summary, would be a cheap companion change.
