### ISSUE TITLE
Rename all .yaml files to .yml in the dataset folder

### ISSUE THREAD

**Issue by nvmbrasserie** [opensanctions/opensanctions#2320]

**Comment by pudo** [comment]
Yes please! And then we get rid of the code that searches `.yaml` so that it becomes a bug :)

**Comment by leonhandreke** [comment]
Claude suggests this pre-commit hook

```yml
repos:
  - repo: local
    hooks:
      - id: check-no-yaml-in-datasets
        name: Disallow .yaml files in datasets directory, use .yml instead
        entry: bash -c 'if find datasets -name "*.yaml" -type f 2>/dev/null | grep -q .; then echo "Error: .yaml files are not allowed in the datasets directory. Found:"; find datasets -name "*.yaml" -type f 2>/dev/null; exit 1; else echo "No .yaml files found in datasets directory - OK"; fi'
        language: system
        pass_filenames: false
        always_run: true
```
