### ISSUE TITLE
Alert when the source data for manually-updated datasets have changed

### ISSUE THREAD

**Issue by jbothma** [opensanctions/opensanctions#515]
We would like to be notified when the source data for a manually-updated dataset has changed.

For data in web pages, that could be done using something like 
```python
h.checksum_check(url) 
```
for an entire page, or
```python
h.checksum_check_element(dom_el)
```
for the content of a specific element on the page.

We could normalise the content first, to minimise the effect of insignificant changes, e.g. using
```python
slugify(el.text_content())
```

The expected checksum needs to be stored somewhere. Some options:
- a new metadata `coverage.checksum` property
- a row before the header of a google sheet
  - This doesn't work nicely for datasets which aren't input via google sheets.

**Comment by pudo** [comment]
I'm thinking a bit more about how we'd store this info.... we sort of want to document the fact that a) the data is frozen and all we can do is alert on source changes, b) what the data of the freezing was, c) the frozen checksum. We're currently using `coverage.end` for b) - which is why I suggested `coverage.checksum`. But it could also be an option to make this a whole extra section?

**Comment by jbothma** [comment]
then the data_url would need to be the actual source. Not sure if we want to rather introduce a `occasionally_extracted_url` for that or something, so that data url matches the data in the dataset.

I don't feel very strongly about putting this under `data` or `coverage`

>  b) what the data of the freezing was

Ohhh you meant date

Just messing about with some yaml

```yaml
coverage:
  frequency: occasional
  end: 2023-10-03
data:
  url: https://google/sheets
  original:
    url: https://yucky/unstructured
    expected_checksum: abc123abc
    content_xpath: 'div[@class="wp-body"]'
```

I don't love the semantics of `data.url is the original unless data.original exists`
