### ISSUE TITLE
Make assertions on the properties of entities in the dataset

### ISSUE THREAD

**Issue by jbothma** [opensanctions/opensanctions#879]
**Is your feature request related to a problem? Please describe.**

when only a portion of entities in a dataset have a particular value, it's easy to write a crawler in a way where you don't realise a value has been dropped, e.g. because of a typo, or because the source has changed.

e.g. 

- a typo in the xpath to get a detail URL fails to look up the href properly, so we keep adding None to the sourceUrl property

**Describe the solution you'd like**

a way to say that an expected proportion of entities have some value, or even a specified number of values, for a given property

e.g.

```yaml
assertions:
  min:
    schema_entities:
      Person: 100
    schema_properties:
      Person:
        name: 100  # this should perhaps be redundant because it's a required field
        sourceUrl: 100  # all entities are expected to have a 
        nationality: 80  # 80% of entities are expected to have a value for nationality
      Sanction:
        endDate: 1  # at least 1% of sanctions are expected to be inactive
```

It could also be useful to specify which values are expected (e.g. which topics), or how many (e.g. 2 URLs per sanction), but this may be out of scope of a first iteration.

**Describe alternatives you've considered**

None

**Additional context**

None
